module.exports = {
  name: 'imagine',
  category: 'ai',
  description: 'AI se high-quality image generate karein bina kisi API key ke.',
  usage: 'imagine <prompt>',
  aliases: ['draw', 'generate'],

  async execute(sock, msg, args, extra) {
    try {
      const text = args.join(' ');
      const prefix = extra.config?.prefix || '.';

      // Agar user ne prompt nahi diya
      if (!text) {
        return extra.reply(`Usage: ${prefix}${this.usage}\nExample: ${prefix}imagine a futuristic cyberpunk city, 4k, realistic`);
      }

      await extra.react('🎨');
      await extra.reply('🎨 Image ban rahi hai, thora intezar karein...');

      // Pollinations AI (No API Key Required)
      const encodedPrompt = encodeURIComponent(text);
      // High quality (1024x1024) aur watermark remove karne ke liye parameters
      const imageUrl = `https://image.pollinations.ai/prompt/${encodedPrompt}?width=1024&height=1024&nologo=true`;

      // Baileys socket ke zariye image send karein
      await sock.sendMessage(
        msg.key.remoteJid, 
        { 
          image: { url: imageUrl }, 
          caption: `*Prompt:* ${text}\n_Generated by ${extra.config?.botName || 'TeamZero-MD'}_` 
        }, 
        { quoted: msg }
      );

      await extra.react('✅');

    } catch (error) {
      console.error("[CMD IMAGINE] Error:", error);
      await extra.reply(`❌ Image generate karne mein masla aaya. Prompt thora change kar ke try karein.`);
    }
  }
};

